development:
  adapter: postgresql
  encoding: unicode
  database: synphony_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: synphony_test
  pool: 5
  username: postgres
  password:
